# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: eslint
        name: lintfix
        entry: npx --prefix ./ui cross-env ESLINT_USE_FLAT_CONFIG=true eslint --fix --cache -c ./ui/eslint.config.mjs
        language: system
        files: \.(vue|js|jsx|ts|tsx)$
      - id: prettier
        name: prettier-format
        language: system
        entry: npx --prefix ./ui prettier --write --list-different
        files: \.(vue|js|jsx|ts|tsx)$


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
