"""modify session models

Revision ID: 005070ea33c3
Revises: aae1df3d40a1
Create Date: 2024-08-11 16:31:05.544089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005070ea33c3"
down_revision: Union[str, None] = "aae1df3d40a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session_messages", sa.Column("parent_message_id", sa.Integer(), nullable=True)
    )
    op.add_column("sessions", sa.Column("schema_name", sa.String(), nullable=True))
    op.drop_column("sessions", "schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("schema", sa.VARCHAR(), nullable=True))
    op.drop_column("sessions", "schema_name")
    op.drop_column("session_messages", "parent_message_id")
    # ### end Alembic commands ###
