"""add session and message models

Revision ID: 3eaebda8643c
Revises: d841b26094db
Create Date: 2024-08-11 15:54:14.705411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3eaebda8643c"
down_revision: Union[str, None] = "d841b26094db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column("tables", sa.String(), nullable=True),
        sa.Column("schema", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.Column("copilot_generated", sa.Boolean(), nullable=True),
        sa.Column("is_system_prompt", sa.Boolean(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=True),
        sa.Column("is_streaming", sa.Boolean(), nullable=True),
        sa.Column("generating", sa.Boolean(), nullable=True),
        sa.Column("actions", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_messages_session_id"),
        "session_messages",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_messages_session_id"), table_name="session_messages")
    op.drop_table("session_messages")
    op.drop_table("sessions")
    # ### end Alembic commands ###
