"""add model column to session

Revision ID: aae1df3d40a1
Revises: 3eaebda8643c
Create Date: 2024-08-11 16:15:34.767231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aae1df3d40a1"
down_revision: Union[str, None] = "3eaebda8643c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("model", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "model")
    # ### end Alembic commands ###
