"""Add data sources table

Revision ID: d841b26094db
Revises: 56f659d3ac0a
Create Date: 2024-07-20 22:04:42.659213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d841b26094db"
down_revision: Union[str, None] = "56f659d3ac0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("type", sa.Enum("SQLite", name="datasourcetype"), nullable=True),
        sa.Column("conn_str", sa.String(), nullable=True),
        sa.Column("conn_str_encrypted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_sources")
    # ### end Alembic commands ###
